---
- name: Create Admin user and set password
  _keystone_user: >
      user="glance"
      password="{{ glance_pass }}"
      tenant="service"
      endpoint="{{ keystone_admin_url }}"
      token="{{ admin_token }}"
      state="present"

- name: Add Glance to Admin role, Service Project (tenant)
  keystone_user: >
    role="admin"
    user="glance"
    tenant="service"
    endpoint="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"

- name: Create the service entity for the Glance service
  keystone_service: >
    name="glance"
    service_type="image"
    description="OpenStack Image service"
    token="{{ admin_token }}"
    state="present"

- name: Create the Image service API endpoints
  keystone_endpoint: >
    service_name="image"
    region="RegionOne"
    public_url="{{ glance_public_url }}"
    internal_url="{{ glance_internal_url }}"
    admin_url="{{ glance_admin_url }}"
    token="{{ admin_token }}"
    state="present"