keystone_host: controller
os_auth: controller
keystone_protocol: http
keystone_hostname: controller
keystone_admin_port: 35357
keystone_internal_port: 5000
keystone_public_port: 5000
keystone_ver: v2.0
keystone_admin_url: "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_admin_port }}/{{ keystone_ver }}"
keystone_internal_url: "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_internal_port }}/{{ keystone_ver }}"
keystone_public_url: "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_public_port }}/{{ keystone_ver }}"