os_auth: controller
nova_controller_mgmt_ip: 10.0.0.11
nova_protocol: http
nova_hostname: controller
nova_admin_port: 8774
nova_internal_port: 8774
nova_public_port: 8774
nova_api_ver: v2
nova_admin_url: "{{ nova_protocol }}://{{ nova_hostname }}:{{ nova_admin_port }}/{{ nova_api_ver}}/%(tenant_id)s"
nova_internal_url: "{{ nova_protocol }}://{{ nova_hostname }}:{{ nova_internal_port }}/{{ nova_api_ver }}/%(tenant_id)s"
nova_public_url: "{{ nova_protocol }}://{{ nova_hostname }}:{{ nova_public_port }}/{{ nova_api_ver }}/%(tenant_id)s"
keystone_auth_uri: http://controller:5000
keystone_auth_url: http://controller:35357

auth_plugin: password

keystone_protocol: http
keystone_hostname: controller
keystone_admin_port: 35357
keystone_internal_port: 5000
keystone_public_port: 5000
keystone_ver: v2.0
keystone_admin_url: "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_admin_port }}/{{ keystone_ver }}"
keystone_internal_url: "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_internal_port }}/{{ keystone_ver }}"
keystone_public_url: "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_public_port }}/{{ keystone_ver }}"

rabbit_host: controller
rabbit_userid: openstack

glance_host: controller