os_auth: controller
glance_protocol: http
glance_hostname: controller
glance_admin_port: 9292
glance_internal_port: 9292
glance_public_port: 9292
glance_admin_url: "{{ glance_protocol }}://{{ glance_hostname }}:{{ glance_admin_port }}"
glance_internal_url: "{{ glance_protocol }}://{{ glance_hostname }}:{{ glance_internal_port }}"
glance_public_url: "{{ glance_protocol }}://{{ glance_hostname }}:{{ glance_public_port }}"
keystone_auth_uri: http://controller:5000
keystone_auth_url: http://controller:35357
keystone_admin_url: http://controller:35357/v3
auth_plugin: password