---
- name: Install EPEL
  yum: name=epel-release state=latest

- name: Enable centos-release-openstack-liberty Repo
  yum: name=centos-release-openstack-liberty

- name: Install OpenStack Packages
  yum: name={{ item }} state=latest
  with_items:
     - chrony
     - python-openstackclient
     - openstack-selinux