---
- name: Install Mariadb
  yum: name={{ item }} state=latest
  with_items:
     - mariadb 
     - mariadb-server
     - python2-PyMySQL
     - MySQL-python

- name: Put Default Mariadb configuration in place
  template: src=mariadb_openstack.cnf.j2 dest=/etc/my.cnf.d/mariadb_openstack.cnf

- name: Start the database service and configure it to start when the system boots
  service: name=mariadb.service state=started enabled=yes