---
- name: Create the service entity for the Identity service
  keystone_service: >
    name="keystone"
    service_type="identity"
    description="OpenStack Identity"
    token="{{ admin_token }}"
    state="present"

- name: Create the service entity for the Identity service identity public
  keystone_endpoint: >
    service_name="keystone"
    region="RegionOne"
    public_url="{{ keystone_public_url }}"
    internal_url="{{ keystone_internal_url }}"
    admin_url="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"

- name: Create Keystone Admin Project (tenant)
  keystone_user: >
    tenant="admin"
    tenant_description="Admin Project"
    endpoint="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"

- name: Create Keystone Service Project (tenant)
  keystone_user: >
    tenant="service"
    tenant_description="Service Project"
    endpoint="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"

- name: Create Keystone Demo Project (tenant)
  keystone_user: >
    tenant="demo"
    tenant_description="Demo Project"
    endpoint="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"

- name: Create Admin user and set password
  _keystone_user: >
      user="admin"
      password="{{ admin_pass }}"
      tenant="admin"
      endpoint="{{ keystone_admin_url }}"
      token="{{ admin_token }}"
      state="present"

- name: Create Admin role
  keystone_user: >
    role="admin"
    user="admin"
    tenant="admin"
    endpoint="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"

- name: Create Demo user and set password
  _keystone_user: >
      user="demo"
      password="{{ demo_pass}}"
      tenant="demo"
      endpoint="{{ keystone_admin_url }}"
      token="{{ admin_token }}"
      state="present"

- name: Create Demo role
  keystone_user: >
    role="user"
    user="demo"
    tenant="demo"
    endpoint="{{ keystone_admin_url }}"
    token="{{ admin_token }}"
    state="present"