---
- include: keystone_prereqs.yml
- include: keystone_install.yml
- include: keystone_service_setup.yml

-- name: Create OpenStack client environment scripts
   templates: src={{ item }}-openrc.sh.j2 dest=~/{{ item }}-openrc.sh state=present
   with_items:
    - admin
    - demo