---
- name: Install rabbit-mq
  yum: name=rabbitmq-server state=latest

- name: Start the message queue service and configure it to start when the system boots
  service: name=rabbitmq-server state=started enabled=yes

- name: Add Openstack User to rabbit-mq-
  rabbitmq_user: user=openstack
                 password=password
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present