---
- name: Install nova packages
  yum: name={{ item }} state=latest
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - python-novaclient

- name: Copy nova.conf in place
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: Populate the Compute database
  command: "su -s /bin/sh -c \"nova-manage db sync\" nova"

- name: Start the Compute services and configure them to start when the system boots
  service: name={{ item }} state=started enabled=yes
  with_items:
    - openstack-nova-api.service
    - openstack-nova-cert.service
    - openstack-nova-consoleauth.service
    - openstack-nova-scheduler.service
    - openstack-nova-conductor.service
    - openstack-nova-novncproxy.service