---
- name: Install MongoDB package
  yum: name={{ item }} state=latest
  with_items:
     - mongodb-server
     - mongodb

- name: Configure the bind_ip key to use the management interface IP address
  lineinfile: dest=/etc/mongod.conf
              regexp=^bind_ip
              line="bind_ip = 10.0.0.11"

- name: Start the MongoDB service and configure it to start when the system boots
  service: name=mongod state=started enabled=yes